feat: Implement QR code scanner with automatic redirection to valid URLs
richbm10/jubmoji.quest pull request #2
Opened 2024-09-11 02:07 UTC by evgongora

**Added QR code scanning functionality with immediate redirection to scanned URLs if valid.**

The `scanner` component was integrated into the quests tab, allowing users to toggle the camera to scan QR codes.

2024-09-11 04:52 UTC, richbm10 requested changes

2024-09-11 04:52 UTC, richbm10 commented on apps/jubmoji-quest/src/pages/index.tsx
> +        {showScanner && <Scanner onResult={handleScannerResult} />}
Let's move our scanner to be into each quest page for a better UX/UI and enable the scanner only for when a quest supports proof of location by having a polygon

2024-09-12 04:17 UTC, evgongora commented on apps/jubmoji-quest/src/pages/index.tsx
> +        {showScanner && <Scanner onResult={handleScannerResult} />}
Added the button inside the quest card when proof type is LOCATION, enhanced UX/UI by making camera full screen and a button to close it.

2024-09-13 04:19 UTC, closed without merging

2024-09-13 04:19 UTC, richbm10 commented
Closing PR as it is outdated and commits were moved into #8